version: '3'

services:
  postgres:
    container_name: postgres_sicredi
    image: postgres:13
    environment:
      POSTGRES_DB: sicredi_data_challenge
      POSTGRES_USER: sicredi
      POSTGRES_PASSWORD: postgresql
    ports:
      - 5432:5432
    # volumes:
      # - './.postgres:/var/lib/postgresql/data/'
      # - ./sql/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
      # - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  desafio-sicredi:
    image: "faker_etl"
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: /spark/bin/spark-submit src/main.py
