# version: '3'

# services:
#   postgres:
#     container_name: postgres_sicredi
#     image: postgres:13
#     environment:
#       POSTGRES_DB: sicredi_data_challenge
#       POSTGRES_USER: sicredi
#       POSTGRES_PASSWORD: postgresql
#     volumes:
#       - './.postgres:/var/lib/postgresql/data/'
#       # - ./sql/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
#       # - ./init-scripts:/docker-entrypoint-initdb.d
#     ports:
#       - 5432:5432

#   python:
#     build: .
#     command: python3 src/main.py
#     volumes:
#       - .:/app
#     depends_on:
#       - postgres
version: '3'

services:
  postgres:
    container_name: postgres_sicredi
    image: postgres:13
    environment:
      POSTGRES_DB: sicredi_data_challenge
      POSTGRES_USER: sicredi
      POSTGRES_PASSWORD: postgresql
    volumes:
      - './.postgres:/var/lib/postgresql/data/'
    ports:
      - 5432:5432

  spark-master:
    image: bitnami/spark:latest
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - SPARK_MODE=master
    volumes:
      - ./data:/data

  spark-worker:
    image: bitnami/spark:latest
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./data:/data

  custom-python-app:
    build: .
    depends_on:
      - postgres
      - spark-master
      - spark-worker
    volumes:
      - ./data:/data


  # pyspark:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile  # Specify the name of your Dockerfile
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - postgres
